### ISSUE TITLE
Server being unable to fetch ping

### ISSUE THREAD

**Issue by ProExis** [Nort721/GodsEye#434] opened 2021-12-04 12:09 UTC
**A issue report**

1) GodsEye version
**Build 49 HotFix-5**
2) Server Version+Fork
**Paper Spigot Build 391 Minecraft version 1.17.1**
3) ProtocolLib version
**4.7.0**
4) Server log
**N/A**
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
![issue1](https://user-images.githubusercontent.com/95529504/144708852-ed742d73-3c92-46ba-83d1-c753da555676.PNG)
6) A very detailed description of the issue
**The server is online, but Minecraft is unable to get a ping from the server thus showing "(no connection)". Everything is up to date only when the plugin is removed it is able to ping the server like usual. When testing the only plugins present were: Protocollib and Godseye.**

**Comment by Nort721** [comment] 2021-12-04 16:17
I found where the issue is and fixed it, a fix will be release in the next version, hopefully will be released next weekend or maybe today will see

**Closed** 2021-12-11 19:03 UTC
Labels: bug, fixed
