### ISSUE TITLE
False movement flag

### ISSUE THREAD

**Issue by QluxpEL** [Nort721/GodsEye#450] opened 2022-01-23 13:59 UTC
1) Build 50 [test Server]
2) No idea, i was in official test server
3) No idea, i was in official test server
4) No acces to it.
5) Video proof ment https://youtu.be/3ULFg38bQbo 
6) If your sneaking and jumping and above you us block your get flagged

**Comment by Nort721** [comment] 2022-01-24 16:53
Thanks for the report, however this report seems to be a duplicate of issue #441, so this specific issue is closed under the duplicate tag

**Closed** 2022-01-24 16:54 UTC
Labels: duplicate
