### ISSUE TITLE
jesus bypass

### ISSUE THREAD

**Issue by QluxpEL** [Nort721/GodsEye#446] opened 2022-01-23 09:08 UTC
1) Build 50 [test Server]
2) No idea, i was in official test server
3) No idea, i was in official test server
4) No acces to it.
5) Video proof ment https://youtu.be/brC7-4zJ5N8
6) Jesus bypass

**Comment by Nort721** [comment] 2022-03-05 16:27
Thanks for the report, although this is a duplicate of ticket #365 which is why I am closing this one

**Closed by Nort721** 2022-03-05 16:27 UTC
Labels: duplicate
