### ISSUE TITLE
issue with godseyegeysermc

### ISSUE THREAD

**Issue by Pikaronga** [Nort721/GodsEye#414] opened 2021-10-26 14:46 UTC
A bug report/issue report should contain:

1) Build 49 HotFix-2
2) 1.16.5 Purpur
3) 4.7.0
4) -
this error cameback with the new godseye version. https://pastebin.com/L16bWqUr

**Comment by Nort721** [comment] 2021-10-30 09:45
This is caused by some issues with GodsEye's obfuscation, it should be resolved in the next GodsEye update

**Closed** 2021-10-31 11:35 UTC
Labels: bug, fixed
